/**
 * constants.js
 *
 * Shared constants for Diverga v9.0 MCP infrastructure.
 * Single source of truth for checkpoint levels used by
 * sqlite-state.js, checkpoint-server.js, and others.
 */

export const CHECKPOINT_LEVELS = {
  CP_RESEARCH_DIRECTION: 'REQUIRED',
  CP_VS_001: 'REQUIRED',
  CP_VS_003: 'REQUIRED',
  CP_THEORY_SELECTION: 'REQUIRED',
  CP_PARADIGM_SELECTION: 'REQUIRED',
  CP_METHODOLOGY_APPROVAL: 'REQUIRED',
  SCH_DATABASE_SELECTION: 'REQUIRED',
  SCH_SCREENING_CRITERIA: 'REQUIRED',
  SCH_API_KEY_VALIDATION: 'REQUIRED',
  CP_VS_002: 'RECOMMENDED',
  CP_SCREENING_CRITERIA: 'RECOMMENDED',
  CP_QUALITY_REVIEW: 'RECOMMENDED',
  CP_INTEGRATION_STRATEGY: 'RECOMMENDED',
  CP_ANALYSIS_PLAN: 'RECOMMENDED',
  CP_SAMPLING_STRATEGY: 'RECOMMENDED',
  CP_CODING_APPROACH: 'RECOMMENDED',
  CP_THEME_VALIDATION: 'RECOMMENDED',
  CP_HUMANIZATION_REVIEW: 'RECOMMENDED',
  SCH_RAG_READINESS: 'RECOMMENDED',
  CP_VISUALIZATION_PREFERENCE: 'OPTIONAL',
  CP_SEARCH_STRATEGY: 'OPTIONAL',
  CP_HUMANIZATION_VERIFY: 'OPTIONAL',
};
