name: meta-analysis
version: "1.0"
description: "Meta-Analytic Research with Effect Size Synthesis"

stages:
  - id: planning
    name: "Stage 1: Planning"
    description: "Define research question and meta-analytic approach"
    artifacts:
      - id: protocol
        name: "Meta-Analysis Protocol"
        generates: "protocol.md"
        template: "protocol.md.j2"
        requires: []
        validation:
          required_fields: [research_question, meta_analysis_type, effect_size_metric]
      - id: effect-size-plan
        name: "Effect Size Decision"
        generates: "effect-size-plan.md"
        template: "effect-size-plan.md.j2"
        requires: [protocol]
        validation:
          required_fields: [effect_size_type, conversion_rules]
    checkpoints:
      - CP_RESEARCH_DIRECTION
      - CP_META_APPROACH

  - id: identification
    name: "Stage 2: Identification"
    description: "Search and screen literature"
    artifacts:
      - id: search-strategy
        name: "Search Strategy"
        generates: "search-strategy.md"
        template: "search-strategy.md.j2"
        requires: [effect-size-plan]
      - id: screening-results
        name: "Screening Results"
        generates: "screening-results.csv"
        requires: [search-strategy]
    checkpoints:
      - CP_DATABASE_SELECTION
      - CP_SCREENING_COMPLETE

  - id: extraction
    name: "Stage 3: Data Extraction"
    description: "Extract effect sizes and study characteristics"
    artifacts:
      - id: extraction-form
        name: "Data Extraction Form"
        generates: "extraction-form.md"
        template: "extraction-form.md.j2"
        requires: [screening-results]
        validation:
          required_fields: [effect_size_fields, moderator_fields, quality_fields]
      - id: extracted-effects
        name: "Extracted Effect Sizes"
        generates: "extracted-effects.csv"
        requires: [extraction-form]
      - id: moderator-coding
        name: "Moderator Coding Scheme"
        generates: "moderator-coding.md"
        template: "moderator-coding.md.j2"
        requires: [extraction-form]
    checkpoints:
      - CP_EXTRACTION_COMPLETE

  - id: analysis
    name: "Stage 4: Statistical Analysis"
    description: "Pool effect sizes and test heterogeneity"
    artifacts:
      - id: analysis-plan
        name: "Analysis Plan"
        generates: "analysis-plan.md"
        template: "analysis-plan.md.j2"
        requires: [extracted-effects]
        validation:
          required_fields: [pooling_method, heterogeneity_tests, moderator_analyses]
      - id: pooled-effects
        name: "Pooled Effect Sizes"
        generates: "pooled-effects.md"
        requires: [analysis-plan]
      - id: forest-plots
        name: "Forest Plots"
        generates: "forest-plots/"
        requires: [pooled-effects]
      - id: heterogeneity-results
        name: "Heterogeneity Analysis"
        generates: "heterogeneity-results.md"
        requires: [pooled-effects]
      - id: moderator-results
        name: "Moderator Analysis Results"
        generates: "moderator-results.md"
        requires: [heterogeneity-results]
    checkpoints:
      - CP_ANALYSIS_COMPLETE
      - CP_HETEROGENEITY_CHECKED

  - id: reporting
    name: "Stage 5: Reporting"
    description: "Generate PRISMA diagram and manuscript"
    artifacts:
      - id: prisma-diagram
        name: "PRISMA Flow Diagram"
        generates: "prisma-diagram.md"
        template: "prisma-diagram.md.j2"
        requires: [moderator-results]
      - id: forest-plot-figures
        name: "Publication-Ready Figures"
        generates: "figures/"
        requires: [prisma-diagram]
      - id: manuscript
        name: "Manuscript Draft"
        generates: "manuscript.md"
        template: "manuscript.md.j2"
        requires: [forest-plot-figures]
    checkpoints:
      - CP_FINAL_REVIEW
      - CP_PUBLICATION_READY
