name: systematic-review
version: "1.0"
description: "PRISMA 2020 Systematic Literature Review"

stages:
  - id: identification
    name: "Stage 1: Identification"
    description: "Define research question and search strategy"
    artifacts:
      - id: protocol
        name: "Review Protocol"
        generates: "protocol.md"
        template: "protocol.md.j2"
        requires: []
        validation:
          required_fields: [research_question, objectives, eligibility_criteria]
      - id: search-strategy
        name: "Search Strategy"
        generates: "search-strategy.md"
        template: "search-strategy.md.j2"
        requires: [protocol]
    checkpoints:
      - CP_RESEARCH_DIRECTION
      - CP_DATABASE_SELECTION

  - id: screening
    name: "Stage 2: Screening"
    description: "Screen papers against inclusion/exclusion criteria"
    artifacts:
      - id: inclusion-criteria
        name: "Inclusion/Exclusion Criteria"
        generates: "inclusion-criteria.md"
        template: "inclusion-criteria.md.j2"
        requires: [search-strategy]
      - id: screening-results
        name: "Screening Results"
        generates: "screening-results.csv"
        requires: [inclusion-criteria]
    checkpoints:
      - CP_SCREENING_CRITERIA
      - CP_SCREENING_COMPLETE

  - id: eligibility
    name: "Stage 3: Eligibility"
    description: "Assess quality and extract data"
    artifacts:
      - id: quality-assessment
        name: "Quality Assessment"
        generates: "quality-assessment.md"
        template: "quality-assessment.md.j2"
        requires: [screening-results]
      - id: data-extraction
        name: "Data Extraction Form"
        generates: "data-extraction.csv"
        requires: [quality-assessment]
    checkpoints:
      - CP_QUALITY_APPRAISAL

  - id: synthesis
    name: "Stage 4: Synthesis"
    description: "Synthesize extracted data"
    artifacts:
      - id: synthesis-plan
        name: "Synthesis Plan"
        generates: "synthesis-plan.md"
        template: "synthesis-plan.md.j2"
        requires: [data-extraction]
      - id: extracted-data
        name: "Extracted Data Summary"
        generates: "extracted-data.md"
        requires: [synthesis-plan]
    checkpoints:
      - CP_SYNTHESIS_APPROACH

  - id: reporting
    name: "Stage 5: Reporting"
    description: "Generate PRISMA diagram and final report"
    artifacts:
      - id: prisma-diagram
        name: "PRISMA Flow Diagram"
        generates: "prisma-diagram.md"
        template: "prisma-diagram.md.j2"
        requires: [extracted-data]
      - id: manuscript
        name: "Manuscript Draft"
        generates: "manuscript.md"
        template: "manuscript.md.j2"
        requires: [prisma-diagram]
    checkpoints:
      - CP_FINAL_REVIEW
